# Generated by Django 4.2.30 on 2026-05-07 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.IntegerField()),
                ('target_title', models.CharField(blank=True, max_length=180)),
                ('nickname', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
