# Generated by Django 4.2.30 on 2026-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinevideo',
            name='video_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
